basic:
    name: 'https://www.opploans.com batch 3'
    environments:
        production: 'https://www.opploans.com'
        staging: ''
        development: ''
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - /rates-and-terms/louisiana
        - /rates-and-terms/michigan
        - /rates-and-terms/minnesota
        - /rates-and-terms/mississippi
        - /rates-and-terms/missouri
        - /rates-and-terms/montana
        - /rates-and-terms/nebraska
        - /rates-and-terms/north-carolina
        - /rates-and-terms/north-dakota
        - /rates-and-terms/ohio
    monitoring:
        days: {  }
        type: daily
        schedule_time: '02:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 15
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
